### PR TITLE
Change alias in queries to snake case.

### PR DESCRIPTION
**Pull request by RaoulDijksman**
This will fix the queries returning lowercase aliases in postgres.

### CODE REVIEW

**Comment by tzookb** [comment]
I am sorry but the tests fail....
Ill fix it and commit to master soon.

1) EndToEndTest::mark_unread_messages_as_read
Undefined property: stdClass::$numOfUnread

/media/tzookb/dynamic/www/meeters/vendor/tzookb/tbmsg/src/Tzookb/TBMsg/Repositories/EloquentTBMsgRepository.php:185
/media/tzookb/dynamic/www/meeters/vendor/tzookb/tbmsg/src/Tzookb/TBMsg/TBMsg.php:318
/media/tzookb/dynamic/www/meeters/vendor/tzookb/tbmsg/tests/EndToEndTest.php:52
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138

2) EndToEndTest::get_number_of_unread_messages
Undefined property: stdClass::$numOfUnread

/media/tzookb/dynamic/www/meeters/vendor/tzookb/tbmsg/src/Tzookb/TBMsg/Repositories/EloquentTBMsgRepository.php:185
/media/tzookb/dynamic/www/meeters/vendor/tzookb/tbmsg/src/Tzookb/TBMsg/TBMsg.php:318
/media/tzookb/dynamic/www/meeters/vendor/tzookb/tbmsg/tests/EndToEndTest.php:69
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
                                     
FAILURES!                            
Tests: 24, Assertions: 44, Errors: 2.

**Comment by RaoulDijksman** [comment]
Oops... sorry my bad... 
I left a comment on the [issue 32](https://github.com/tzookb/tbmsg/issues/32), you forgot `userId`

**Comment by tzookb** [comment]
now it is done with `xxxx` please check, and lets close this tiny bug.

and userId is not used, I'll remove it soon.

**Comment by RaoulDijksman** [comment]
Haha yes lets close it, xD we have been on this for way too long. My bad, sorry. 

What do you mean with `xxxx`?

**Comment by tzookb** [comment]
hhh sorry I mean "   `    "

**Comment by tzookb** [comment]
sorry it wasnt pushed.

here https://github.com/tzookb/tbmsg/commit/9a3868476fb7ebb69b56dfec01dc498be19dbae5

**Pull request closed without merging**
