### PR TITLE
Add missing qutoes to userId

### PR DESCRIPTION
**Pull request by RaoulDijksman**
All test return green.

### CODE REVIEW

**Comment by tzookb** [comment]
thanks but this is already done with ` single quotes in my last commit, and as I said, the userId is never used and will be removed.

Please confirm that the last commit works with postgres

**Comment by RaoulDijksman** [comment]
The last commit that i see is [#32 fixed the postgres aliases problem](https://github.com/tzookb/tbmsg/commit/77d6cd9a4ce1d46d1581f600b749aa8206530eb0) .
In that commit you forgot quotes on the `userId` for the getConverations() query.

**Comment by RaoulDijksman** [comment]
I see your last commit now. 9a38684 
But this doesn't work. Sorry xD
This query doesn't work on postgres, mariaDB and MySQL (only on strict mode).
You used the \` (grave accent) quote which are for values. Use the \` (single quote). Single quotes are used to indicate the beginning and end of a string in SQL. Double quotes generally aren't used in SQL even though they work the same as single quotes, but that can vary from database to database.
https://stackoverflow.com/questions/1992314/what-is-the-difference-between-single-and-double-quotes-in-sql

**Comment by tzookb** [comment]
hhhhhhhhhh I dont know what to use any more....

take my last to commits change the quotes to whatever you want, run the tests make sure they run and I'll add your pull request.

**Comment by RaoulDijksman** [comment]
Haha ok i will.

On a side note:
- Grave accent ( \` \` ) These are known as backtick in SQL. MySQL uses these to escape MySQL reserved words that's why these are used in values to escape them.
- Single quotes ( ' ' ) Single quotes are used to indicate the beginning and end of a string.
- Double quotes ( " " ) Double quotes generally aren't used in SQL even though they work the same as single quotes.

**Comment by tzookb** [comment]
thanks :+1:  waiting for the pull request and please make sure tests passes...

you will need phpunit and sqlite installed

**Comment by RaoulDijksman** [comment]
I now see why you used double quotes the first time. The php sting starts with single quotes. Laravel did the same thing with Eloquent. Do you want me to keep your php quotes single and use double quotes for the SQL query? Or do you want me to follow SQL standards and change the php quotes?

**Comment by tzookb** [comment]
I gave up :/   hh
just make it work with as minimal changes needed to make it work for you and for others :)

**Pull request closed without merging**
